Changes are made in Dog claas, object is created in Test class
CevahirBb/AnimalProject pull request #3
Opened 2024-04-01 14:59 UTC by RosanaKmetovikj

Changes are made and are ready for review.
![Screenshot 2024-04-01 165607](https://github.com/CevahirBb/AnimalProject/assets/164254613/f96f0036-ad99-4dfc-acfa-307be877b179)

2024-04-01 15:06 UTC, CevahirBb commented on src/Dog.java
> +    String name;
I already made name variable under dog class

2024-04-01 15:07 UTC, RosanaKmetovikj commented on src/Dog.java
> +    String name;
okay, when we are resolvig our conflic we can keep your changes in the code.

2024-04-01 15:15 UTC, PatelSarita commented on src/Dog.java
> +    String name;
I have created breed variable in dog class

2024-04-01 15:15 UTC, CevahirBb commented on src/Dog.java
> +    String name;
yes that is okay

2024-04-01 15:26 UTC, PatelSarita requested changes
please have a look.

2024-04-01 15:26 UTC, PatelSarita commented on src/Test.java
> +Dog dog1=new Dog(7,'M',"Labrador","Mike");
I have also made dog1 object

2024-04-01 20:54 UTC, PatelSarita commented on src/Dog.java
> +    String name;
ok ...thank you

2024-04-03 20:54 UTC, CevahirBb approved these changes

2024-04-03 20:58 UTC, merged

2024-04-03 21:00 UTC, PatelSarita reviewed
looks ok

2024-04-03 21:01 UTC, PatelSarita reviewed
looks fine