Sarita
CevahirBb/AnimalProject pull request #4
Opened 2024-04-01 15:31 UTC by PatelSarita

Have a look on my code and please review
![Screenshot 2024-04-01 173051](https://github.com/CevahirBb/AnimalProject/assets/164254624/d0269720-4132-4c67-9fcd-1aab6df35309)

2024-04-01 15:35 UTC, CevahirBb requested changes
can you look yor sub class

2024-04-01 15:35 UTC, CevahirBb commented on src/Dog.java
> -    String name;
i already made name variable to our sub class

2024-04-01 21:52 UTC, CevahirBb requested changes

2024-04-03 20:52 UTC, CevahirBb approved these changes

2024-04-03 21:22 UTC, RosanaKmetovikj approved these changes

2024-04-03 21:22 UTC, CevahirBb approved these changes

2024-04-03 21:23 UTC, merged

2024-04-03 21:23 UTC, RosanaKmetovikj approved these changes